substitutions:
  friendly_name: Zehnder ComfoAir Q
  device_name: esp32-ca350
  device_description: Ventilation system
  filter_time: 5s
  filter_send_every: "1"
  filter_window_size: "3"

packages:
#  device_base: !include boards/esp32-s2-wifi.yml
#  binary_sensors: !include packages/binary_sensors.yml
#  board: !include packages/board.yml
#  button: !include packages/button.yml
#  canbus: !include packages/canbus.yml
#  climate: !include packages/climate.yml
#  common: !include packages/common.yml
#  fan: !include packages/fan.yml
#  select: !include packages/select.yml
#  sensors: !include packages/sensors.yml
#  switch: !include packages/switch.yml
# text_sensors: !include packages/text_sensors.yml
  remote_package:
    url: https://github.com/veenstrap/esphome-zehnder-comfoair
    refresh: 0s
    files: [ 
      boards/esp32-eth0.yml,
      packages/binary_sensors.yml,
      packages/board.yml,
      packages/button.yml,
      packages/canbus.yml,
      packages/climate.yml,
      packages/common.yml,
      packages/fan.yml,
      packages/select.yml,
      packages/sensors.yml,
      packages/switch.yml,
      packages/text_sensors.yml,
    ]

dashboard_import:
  package_import_url: github://veenstrap/esphome-zehnder-comfoair/zehnder-comfoair-q-wifi-v2.yml@main
  import_full_config: true

  
external_components:
  - components: [ zehnder_comfoair_q ]
    # uncomment for local dev
    # source: components
    source: github://veenstrap/esphome-zehnder-comfoair@main
    
esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  comment: ${device_description}
  project:
    name: SkullboyNL.esphome-zehnder-comfoair(author yoziru) 
    version: "2025.7.1"

logger:
  level: INFO
  logs:
    canbus: INFO

api:

ota:
  platform: esphome

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

captive_portal:

web_server:
  port: 80

    
# See docs: https://github.com/michaelarnauts/aiocomfoconnect/blob/master/docs/PROTOCOL-PDO.md
zehnder_comfoair_q:
  id: comfoair
  request_ids:
    [
      16,
      49,
      54,
      55,
      65,
      66,
      67,
      81,
      82,
      117,
      118,
      119,
      120,
      121,
      122,
      128,
      129,
      130,
      192,
      209,
      210,
      211,
      212,
      212,
      213,
      214,
      215,
      216,
      217,
      218,
      220,
      221,
      225,
      227,
      274,
      275,
      276,
      277,
      278,
      290,
      291,
      292,
      293,
      294,
    ]
